// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package login

import mock "github.com/stretchr/testify/mock"

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

// getAllUsers provides a mock function with given fields:
func (_m *MockIRepository) getAllUsers() []User {
	ret := _m.Called()

	var r0 []User
	if rf, ok := ret.Get(0).(func() []User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]User)
		}
	}

	return r0
}
